<?php


/**
 * Implementation of hook_menu
**/
function citation_lookup_menu() {
  $items = array();

  $items['citation_lookup'] = $items['citation_lookup/%'] = array(
    'title' => 'Citation Lookup Tool',
    'file' => 'citation_lookup.app.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('citation_lookup_form', 1),
    'access arguments' => array('access citation lookup tool'),
  );

  $items['citation_lookup'] += array(
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => 50,
  );

  return $items;
}


/**
 * Implementation of hook_permission
**/
function citation_lookup_permission() {
  return array(
    'access citation lookup tool' => array(
      'title' => t('access citation lookup tool'),
      'description' => t('access citation lookup tool'),
    ),
  );
}
