<?php

/**
 * @file
 * Feeds plugins for importing VIVO content.
 */

/**
 * Implements hook_feeds_plugins().
 */
function ldimport_vivo_feeds_plugins() {
  $info['LdImportVivoClassFetcher'] = array(
    'name' => 'VIVO Class Fetcher',
    'description' => 'Fetches all individuals of a particular class from a public VIVO site.',
    'handler' => array(
      'parent' => 'LdImportFetcher',
      'class' => 'LdImportVivoClassFetcher',
      'file' => 'LdImportVivoClassFetcher.inc',
      'path' => drupal_get_path('module', 'ldimport_vivo') . '/plugins',
    ),
  );
  return $info;
}
